### ISSUE TITLE
Avatar Links do not work

### ISSUE THREAD

**Issue by Keelan** [psegovias/twando#1]
Either under search or logs. The Avatar links to 

``` html
<a href="https://twitter.com/account/redirect_by_id?id=RANDOMNUMBERS" target="_blank">
```

Which i guess is suppose to the the ID of the user, but it doesn't work.

> Sorry, that page doesn’t exist!
> You can search Twitter using the search box below or return to the homepage.

Seems it needs to me changed to usernames instead.

**Edit:**

**Actually:** https://twitter.com/intent/user?user_id=XXX

Thanks for pull approval.

**Comment by blackthornecl** [comment]
No problem! Thanks for your help :+1:
