### ISSUE TITLE
0.6.1 (still?) has the redirect_by_id issue.

### ISSUE THREAD

**Issue by ghost** [psegovias/twando#24]
The 0.6.1 [Changelog](http://www.twando.com/help/changelog/) mentions: "_Fixed redirect_by_id issue due to Twitter removing support for this._" My **include_top.php** reads: _TWANDO_VERSION','0.6.1'_.

Nevertheless, when I click on any account image thumbnail in **Search to Follow** >> **Tweet based** or **User based** >> **Search Results**, I get the "_Sorry, that page doesn’t exist!_" [error message page](https://twitter.com/account/redirect_by_id?id=000000000) from Twitter.

**Comment by blackthornecl** [comment]
Use this installation, not from site.
