### ISSUE TITLE
fresh install

### ISSUE THREAD

**Issue by random-robbie** [psegovias/twando#5]
Notice: Undefined index: HTTPS in /var/www/twitter/inc/include_top.php on line 30

Notice: Constant BASE_LINK_URL already defined in /var/www/twitter/inc/include_top.php on line 34

Notice: Undefined index: return_url in /var/www/twitter/index.php on line 10

Notice: Undefined index: a in /var/www/twitter/index.php on line 18

Notice: Undefined index: a in /var/www/twitter/index.php on line 46

have i missed anything i have changed cron and default username and password

**Comment by random-robbie** [comment]
I can see i have errors turned on i've had to add if (!empty($_POST["a"])) { around two places on the index.php and might have to do some more as the if statements need to also check if the $_POST is set

**Comment by aaalaslamiii** [comment]
Very special

**Comment by blackthornecl** [comment]
try now.

**Comment by random-robbie** [comment]
i seen all the pull requests have been merged now.

one thing you will need to do is update the twitter oauth best using composer so users can just run composer if it needs an update

**Comment by blackthornecl** [comment]
Can you pull it?
